name: publish next version package

on:
  release:
    types: [prerelease]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NODE_VERSION: 16

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org"

      - name: Install dependency
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run release

      - name: Publish
        run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
